twig:
    file_name_pattern: '*.twig'

    globals:
        app_name: '%env(APP_NAME)%'
        app_email_name: '%env(MAILER_NAME)%'
        app_email_address: '%env(MAILER_ADDRESS)%'
        app_no_reply_email_address: '%env(NO_REPLY_MAILER_ADDRESS)%'
        app_default_locale: '%default_locale%'
        app_supported_locales: '%supported_locales%'

    form_themes: ['bootstrap_5_layout.html.twig']

    date:
        format: d/m/Y H:i
        interval_format: '%%d'
        timezone: '%env(APP_TIMEZONE)%'

    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: ' '

#    paths:
#        # point this wherever your images live
#        '%kernel.project_dir%/public/img': img

when@test:
    twig:
        strict_variables: true
